import { Coffee } from '@/@types/Coffe'

export const coffeeList: Coffee[] = [
  {
    id: 1,
    price: 9.9,
    subtitle: 'O tradicional café feito com água quente e grãos moídos',
    tags: ['tradicional'],
    title: 'Expresso Tradicional',
  },
  {
    id: 2,
    price: 9.9,
    subtitle: 'Expresso diluído, menos intenso que o tradicional',
    tags: ['tradicional'],
    title: 'Expresso Americano',
  },
  {
    id: 3,
    price: 9.9,
    subtitle: 'Café expresso tradicional com espuma cremosa',
    tags: ['tradicional'],
    title: 'Expresso Cremoso',
  },
  {
    id: 4,
    price: 9.9,
    subtitle: 'Bebida preparada com café expresso e cubos de gelo',
    tags: ['tradicional', 'gelado'],
    title: 'Expresso Gelado',
  },
  {
    id: 5,
    price: 9.9,
    subtitle: 'Meio a meio de expresso tradicional com leite vaporizado',
    tags: ['tradicional', 'com leite'],
    title: 'Café com Leite',
  },
  {
    id: 6,
    price: 9.9,
    subtitle: 'Uma dose de café expresso com o dobro de leite e espuma cremosa',
    tags: ['tradicional', 'com leite'],
    title: 'Latte',
  },
  {
    id: 7,
    price: 9.9,
    subtitle: 'Bebida com canela feita de doses iguais de café, leite e espuma',
    tags: ['tradicional', 'com leite'],
    title: 'Capuccino',
  },
  {
    id: 8,
    price: 9.9,
    subtitle: 'O tradicional café feito com água quente e grãos moídos',
    tags: ['tradicional'],
    title: 'Expresso Tradicional',
  },
  {
    id: 9,
    price: 9.9,
    subtitle: 'Café expresso misturado com um pouco de leite quente e espuma',
    tags: ['tradicional', 'com leite'],
    title: 'Macchiato',
  },
  {
    id: 10,
    price: 9.9,
    subtitle: 'Café expresso com calda de chocolate, pouco leite e espuma',
    tags: ['tradicional', 'com leite'],
    title: 'Mocaccino',
  },
  {
    id: 11,
    price: 9.9,
    subtitle: 'Bebida feita com chocolate dissolvido no leite quente e café',
    tags: ['especial', 'com leite'],
    title: 'Chocolate Quente',
  },
  {
    id: 12,
    price: 9.9,
    subtitle: 'Drink gelado de café expresso com rum, creme de leite e hortelã',
    tags: ['especial', 'alcoólico', 'gelado'],
    title: 'Cubano',
  },
  {
    id: 13,
    price: 9.9,
    subtitle: 'Bebida adocicada preparada com café e leite de coco',
    tags: ['especial'],
    title: 'Havaiano',
  },
  {
    id: 14,
    price: 9.9,
    subtitle: 'Bebida preparada com grãos de café árabe e especiarias',
    tags: ['especial'],
    title: 'Árabe',
  },
  {
    id: 15,
    price: 9.9,
    subtitle: 'Bebida a base de café, uísque irlandês, açúcar e chantilly',
    tags: ['especial', 'alcoólico'],
    title: 'Irlandês',
  },
]
